### ISSUE TITLE
Determination of the location with GeoDB Cities

### ISSUE THREAD

**Issue by Swetlana-K** [sametimesameplace/backend#70]
If a negative longitude or latitude is used, the location is not created.

**Comment by Termuellinator** [comment]
I've already solved that with https://github.com/sametimesameplace/backend/compare/dev...mat-negativecoords - you can give that a test if you want, i still want to include some tests before opening a PR.

**Comment by SteffenPyGo** [comment]
Fix approved.

**Comment by Termuellinator** [comment]
fixed by https://github.com/sametimesameplace/backend/pull/72
